name: CI No Log

on:
  workflow_dispatch:
  pull_request:
    branches:
      - unit-test-frozen-clock
  push:
    branches:
      - unit-test-frozen-clock

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: pip install python-dateutil && tox -e py
